### ISSUE TITLE
choose section drop down

### ISSUE THREAD

**Issue by RyanMcPherson7** [wobbethan/EGN4912#74]
![Screenshot 2024-02-12 at 12 03 55 PM](https://github.com/wobbethan/EGN4912/assets/71467277/a2cd39b8-eab0-4827-a9c9-053dd734dc59)
- title doesn't change when user selects different section, it's always `all sections`
- need clearer hover effect for options and dropdown itself
- keyboard navigation doesn't go to drop down options (accessibility)

**Comment by wobbethan** [comment]
Name and hover effect added, drop down is custom component, adding keyboard integration scary
